POST http://localhost:7071/api/certificate
Content-Type: application/json

{
    "certificateName": "wildcard-hollan-cloud",
    "dnsNames": [ "*.hollan.cloud" ],
    "containerAppId": "/subscriptions/subId/resourceGroups/d-certtest/providers/Microsoft.App/containerApps/certtest",
    "containerAppDomain": "test.hollan.cloud"
}

###
GET http://localhost:7071/api/apps

###
GET http://localhost:7071/api/dns-zones